sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image and push
      script:
      - docker login -u="${DOCKER_HUB_USERNAME}" -p="${DOCKER_HUB_PASSWORD}"
      - docker build -t kajisha/alpinist .
      - docker images
      - docker push kajisha/alpinist

notifications:
  webhooks:
    - https://idobata.io/hook/travis_ci/94af1658-0d32-485f-90e0-0dd56cc3b44d
